### ISSUE TITLE
Lag in drag drop

### ISSUE THREAD

**Issue by samir-kamble** [highcharts/draggable-points#74] opened 2017-09-04 08:06 UTC
Hello Sir,

Great plugin first of to congratulate. I wanted it always for my projects. Now I am using in one of my Angular JS project and it worked well. Only problem is when I drag my mouse taking in account a point it comes to drop position after a 1 seconds lag.

do you have any idea about it or which plugin might have causing the same?

Regards,
Sam.

**Comment by TorsteinHonsi** [comment] 2017-09-05 06:54
That's a lot of lag. I'm afraid we have to see a live demo in order to have an idea of why.

**Comment by samir-kamble** [comment] 2017-09-05 07:34
Cannot have a local demo of the thing as it is local development enviorment.

**Comment by TorsteinHonsi** [comment] 2017-09-05 08:25
Okay, sorry then we can't help you since we don't have anything to debug on. I'm closing this, please reopen if you can reproduce it on jsFiddle.

**Closed by TorsteinHonsi** 2017-09-05 08:25 UTC
